title: "ModelDB"
description: A system to manage ML models
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky
markdown: kramdown

gems:
  - jekyll-mentions
  
kramdown:
   # Use GitHub flavored markdown, including triple backtick fenced code blocks
   input: GFM
   # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
   syntax_highlighter: rouge
   syntax_highlighter_opts:
     # Use existing pygments syntax highlighting css
     css_class: 'highlight'
